name: DomGignac
favicon: null
layout_spectrum: 0.89815
typography_spectrum: 0.31827
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#fefefe'
    - '#b5aea4'
    - '#978f84'
    - '#6e5443'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
